run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sunquakes/snowredis
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoinits
    - gochecknoglobals
    - lll
    - godox
    - gocognit
    - whitespace
    - wsl
    - funlen
    - goerr113
    - testpackage
    - nlreturn
    - gomnd
    - exhaustivestruct
    - paralleltest
    - tparallel
    - thelper
    - ifshort
    - exhaustruct
    - varnamelen
    - gci
    - gocritic
    - wrapcheck
    - interfacer
    - scopelint
    - musttag
    - ireturn
    - forcetypeassert
    - cyclop
    - maintidx
    - errchkjson
    - goheader
    - containedctx
    - contextcheck
    - revive
    - nosprintfhostport
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

issues:
  exclude-use-default: false